### ISSUE TITLE
lambda functions in chaining and pandas column attribute shorthand

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#130]
If I have a df with one column `a`, and I want to do:
- create a new column `b = a+1`
- create a new column `c = b+1`

Then we currently can't chain it. We would have to store an intermediate in order to reference the new column.
```
df = df.assign(b = df['a']+1)
df = df.assign(c = df['b']+1)
```

We can instead create a lambda that gives us a temporary name for the new assigned df https://pandas.pydata.org/docs/user_guide/dsintro.html#assigning-new-columns-in-method-chains

```
df.assign(
        b = df['a'] + 1
   ).assign(
        c = lambda x : x['b'] + 1
)
```

Similarly, we can do `x.b` instead of `x['b']` for brevity. Might be nice to teach and use that where possible.

**Comment by joelostblom** [comment]
I was thinking about this when I reviewed chapter 5 as well. There we use `assign` with the original name of the dataframe and it works because we don't do any updates to the column in the same chain. However, we don't explain this caveat to students and I think it is likely we are setting them up for unintended side effects from the calls to `assign` since they don't know of this caveat. My vote here would actually be to not teach `assign` in an intro level course like dsci 100 and just stick to separate lines when creating new columns. I could see an argument for having an optional page in the textbook for advanced  students that dives deeper into method chaining and covers `assign`, `lambda`, and `apply`, but that these are not part of the regular textbook curriculum (ref #100 )

> Similarly, we can do x.b instead of x['b'] for brevity. Might be nice to teach and use that where possible.

I don't think it is worthwhile to teach this since it doesn't work for column names with special characters, most notably spaces which I'm sure students will come across, and will make it ambiguous if there is a column with the same name as a dataframe method. Better to keep it simple and teach one way that always works in my opinion.
