### ISSUE TITLE
Import updates to missing data, confusion matrices, precision/recall if merged in R

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#177]
Referring to PRs:
- https://github.com/UBC-DSCI/introduction-to-datascience/pull/508
- https://github.com/UBC-DSCI/introduction-to-datascience/pull/509

Obviously only do this if they get merged in R version

**Comment by trevorcampbell** [comment]
Both PRs were merged -- so we need to update Py book with this stuff too.

**Comment by joelostblom** [comment]
It's great that we merged this missing data section, I just noticed that we use `dropna` in worksheet 4 without covering it in the textbook, so it will be helpful when it's in chapter 3. I will rework the worksheet as if this will be covered in ch3. It would be helpful if the chapter included dropping missing values only from a subset of columns since this is how we use it in the worksheet.

**Comment by trevorcampbell** [comment]
@joelostblom missing data and precision/recall are both in Chapter 5 -- Classification I

I wouldn't worry about some things appearing in worksheets before in the book, as long as it's just small stuff (like `dropna`) and we explain it clearly when it's introduced
