### ISSUE TITLE
Show regression predictions for test data like in the assignments instead of for all data?

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#212]
Details in https://github.com/UBC-DSCI/introduction-to-datascience-python/pull/207/files#r1299125230

**Comment by trevorcampbell** [comment]
Since we do a uniform grid of predictions (and plot scatter data overlaid) in classification, I'd want to keep that pattern in regression. I'm not 100% opposed to just plotting the test data instead of the full data frame -- that was an arbitrary choice without thinking much originally I think -- but it won't change much and the plots look fine as-is. Closing
