### ISSUE TITLE
Recommend nlargest/nsmallest over sorting and slicing

### ISSUE THREAD

**Issue by joelostblom** [UBC-DSCI/introduction-to-datascience-python#35]
While `sort_values` + `iloc` is similar to `arrange` and `slice` in R, is not as effective or clear as `nlargest`/`nsmallest` in pandas, so I think we should add and recommend the later (but still keeping at least `sort_values` since that is useful for other things). In R, we should really use `slice_min` and `slice_max` for this as that it also more efficient than sorting all values first.

**Comment by trevorcampbell** [comment]
It's useful to introduce the general idea of `.iloc` now though, so I think it's still valuable to do it this way.

But we can definitely add `nlargest` and `nsmallest` as a "here is a more specialized way of doing this that is a bit cleaner". 

Let's do the individual chapter-specific edits first, and come back to this for a global pass later. I would imagine after chapter-specific passes we'll need to look closely at wrangling again, since that's probably where R and Py differ the most...

**Comment by trevorcampbell** [comment]
We have done this in Py -- I believe we introduce nlargest/smallest in viz first (but it may actually appear before that, needs investigation)

![image](https://github.com/UBC-DSCI/introduction-to-datascience-python/assets/5981307/1b2a2b57-d7d1-423a-bf06-7d6612a6ce85)

**Comment by trevorcampbell** [comment]
Yep viz is the first place the "get the X largest / smallest items" happens after Ch1 (where more basic methods are preferred over specialized things). So this is handled now (in both R and Py).
