### ISSUE TITLE
Get rid of multiple source formats

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#45]
Right now our `source/` dir has `.ipynb`, `.md`, and `.py` files all linked to each other. Generally it is bad practice to have duplicated information / autogenerated output in a github repository, and it's not clear which of these file formats should be treated as the "main source".

I suggest we keep only the `.md` files (as they are plaintext) version controlled, `.gitignore` the `.ipynb` and `.py`, and then each of us can edit locally by pairing a (non-version-controlled) `.ipynb` to the `.md` if needed for easier development.

**Comment by joelostblom** [comment]
I agree with removing all duplicated files as I find that confusing as well. I would be inclined to keep the ipynb files instead of the md files in the repo. I think it can be useful to the outputs in the notebooks themselves even if we mostly use the min the context of the built site. I also like that it doesn't rely on us using the Jupytext extension locally and is the native format for the notebooks.

If the main problem with ipynb files is seeing a more useful diff, then I recommend opting in for the rich diff preview via the Google forms link in this discussion https://github.com/community/community/discussions/37376. It will also show diffs for changes to images in the output which can be helpful for charts (although there are some caveats with altair in that specific regard).

**Comment by trevorcampbell** [comment]
>  I would be inclined to keep the ipynb files instead of the md files in the repo. I think it can be useful to the outputs in the notebooks themselves 

I'm very strongly against ever committing output to github -- it has caused me issues frequently in the past when people commit gigantic outputs that blow up repo size. And ipynb notebooks are very prone to people accidentally committing outputs, so I try to avoid them in GH repos where possible.

But I agree that it might be nice to have the ipynb (edit: I've changed my mind and am in `.md` camp, see below), if we got more useful diffs and could prevent committing output

Have you ever tried using a pre-commit hook? I wonder if that would prevent the more annoying issues with committed output... e.g. https://github.com/kynan/nbstripout

**Comment by trevorcampbell** [comment]
Ah, you know what... after thinking about it a bit more, I am pretty convinced that we should treat `.md` files as the true source. A few reasons:
- For making quick edits, it's much easier to work right in the `.md` file myself (I use `vim`). You can still create a notebook in jupytext, and work there if you feel the need. 
- No external tools required for useful diffs.  
- No risk of people committing gigantic outputs
- It gives easier access to more fine-grained control over an exact source file (instead of forcing one to use the jupyter gui)
- I can easily edit on another machine over ssh
- It's more readable and workable as plaintext. So if we ever want to port this material to some other format (not jupyterbook), it'll be much easier to do that using the `.md` files, not `.ipynb`s. One could just use jupytext at the end of the day to do that, but then we're relying again on an external tool for that.

**Comment by joelostblom** [comment]
Overall, I am onboard with trying to use md as the source format. It has been my experience in the past that I usually end up missing the ipynb for one reason or the other, but maybe I will learn to love it this time =) Since we in this project have the book built with all the outputs, I think there is less need for seeing outputs in the ipynbs during review (especially if we have the automatic deploy previews set up). My thoughts on the some of the specific comments:

> I'm very strongly against ever committing output to github / No risk of people committing gigantic outputs

I actually think this is quite useful when working on data projects where we often want to review the outputs when reviewing PRs. I hear the pain of getting huge outputs committed in the repo accidentally, but that is something that should be caught in PR review in my opinion.

> Have you ever tried using a pre-commit hook?

I recently started using a pre-commit hook for cleaning execution numbers which work really well https://stackoverflow.com/a/74104683/2166823, but the downside is having multiple people set it up (which is more complicated than having multiple people installing the jupytext extension).

> For making quick edits, it's much easier to work right in the .md file myself (I use vim).

Agree with this and I also find it a convenience to fire up vim and make a small edit.

>  It's more readable and workable as plaintext. So if we ever want to port this material to some other format (not jupyterbook), it'll be much easier to do that using the .md files, not .ipynbs. One could just use jupytext at the end of the day to do that, but then we're relying again on an external tool for that.

I think this is something that could be handled after the fact via conversion tools and we are relying on jupytext for our workflow now too. I don't think it is a big point overall though.

> No external tools required for useful diffs.
   
I think my ideal notebook source format would be .md natively supported by JupyterLab and with outputs optionally stored as a single long line starting with an indication of how many bytes/characters it was. Easy to read and would not clutter the diffs since changes in outputs would just be one line, but would indicate when there were changes to the outputs and could be rendered online (e.g. maybe a base64 encoded image).

**Comment by trevorcampbell** [comment]
> Overall, I am onboard with trying to use md as the source format

OK! Let's go with that then. I'll merge the PR.

> but that is something that should be caught in PR review in my opinion.

It still exists in the commit history though (unless you don't merge and delete the branch entirely), so it still takes up space and slows down clones / etc ;)

Thanks for the brainstorming here!

**Comment by trevorcampbell** [comment]
Closed by #46

**Comment by joelostblom** [comment]
Just adding a note here that I think the workflow with md files has been working really well and I haven't missed the ipynb outputs since we always build the book anyways when reviewing PRs!
