### ISSUE TITLE
Explaining `.query`?

### ISSUE THREAD

**Issue by trevorcampbell** [UBC-DSCI/introduction-to-datascience-python#54]
An idea that was raised was to swap out `[]` with `.query` for dataframes.

So instead of 
```
df[df["col"] == val]
```
we would have
```
df.query("col == val")
```

I don't think it's worth changing this during the first major polished version, but worth discussing for future versions.

**Comment by joelostblom** [comment]
I mostly use query myself but an important consideration for novices is that the pandas docs and most online forums are dominated by the [] approach since this is the default in pandas. For complicated filtering operations I find I sometimes have to go back to [] myself and we don't want students to have to switch between the two. Tab completion also does not work for query and we would still use [] for column selection regardless of what we choose for row filtering.

**Comment by joelostblom** [comment]
We decided to include a short explanation of query in the wrangling chapter but to stick with the traditional `df[bool]` syntax for filtering in general.
